"""add structured_pitch to reports

Revision ID: 060b35a6f0ca
Revises: 78a9307d24a6
Create Date: 2026-07-09 16:10:52.305572

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '060b35a6f0ca'
down_revision: str | None = '78a9307d24a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('structured_pitch', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'structured_pitch')
    # ### end Alembic commands ###
