"""add avatar_conversations table

Revision ID: 0e957ea7e000
Revises: d6cae1a85a3b
Create Date: 2026-05-12 16:16:14.259389

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e957ea7e000'
down_revision: str | None = 'd6cae1a85a3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_conversations',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_conversation_id', sa.String(length=128), nullable=False),
    sa.Column('conversation_url', sa.String(length=1024), nullable=False),
    sa.Column('replica_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=False),
    sa.Column('interactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'error', name='avatar_conversation_status'), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_conversations_provider_conversation_id'), 'avatar_conversations', ['provider_conversation_id'], unique=True)
    op.create_index(op.f('ix_avatar_conversations_session_id'), 'avatar_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_avatar_conversations_status'), 'avatar_conversations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatar_conversations_status'), table_name='avatar_conversations')
    op.drop_index(op.f('ix_avatar_conversations_session_id'), table_name='avatar_conversations')
    op.drop_index(op.f('ix_avatar_conversations_provider_conversation_id'), table_name='avatar_conversations')
    op.drop_table('avatar_conversations')
    # ### end Alembic commands ###
