"""add perception_analysis and events to avatar_conversations

Revision ID: 78a9307d24a6
Revises: 0e957ea7e000
Create Date: 2026-05-12 22:56:38.060219

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78a9307d24a6'
down_revision: str | None = '0e957ea7e000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar_conversations', sa.Column('perception_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('avatar_conversations', sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar_conversations', 'events')
    op.drop_column('avatar_conversations', 'perception_analysis')
    # ### end Alembic commands ###
